name: Release and Build

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 1.23
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Run make build
        run: make build

      - name: Upload built binaries
        uses: actions/upload-artifact@v4
        with:
          name: orbital-binaries
          path: build/

  docker_build_and_push:
    name: Package
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU (for cross-building)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: orbital-binaries
          path: build/

      - name: Build and push Docker image
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          TAGS="latest,$TAG_NAME"
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg APP_NAME=orbital \
            $(echo $TAGS | tr ',' '\n' | sed 's/^/-t ryuunosukeds3\/orbital:/') \
            --push .

  update_raspberry_cluster:
    name: Update raspberry-cluster repo
    runs-on: ubuntu-latest
    needs: docker_build_and_push
    steps:
      - name: Checkout raspberry-cluster repo
        uses: actions/checkout@v3
        with:
          repository: RyuunosukeDS3/raspberry-cluster
          token: ${{ secrets.RELEASE_TOKEN }}
          path: raspberry-cluster

      - name: Update orbital-values.yaml with current tag
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          FILE="raspberry-cluster/orbital/helm/orbital-values.yaml"

          if ! command -v yq &> /dev/null; then
            echo "Installing yq..."
            sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod +x /usr/local/bin/yq
          fi

          echo "Updating image.tag to $TAG_NAME in $FILE"
          yq eval ".image.tag = \"$TAG_NAME\"" -i "$FILE"

          echo "Modified file:"
          cat "$FILE"

      - name: Commit and push changes
        run: |
          cd raspberry-cluster
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add orbital/helm/orbital-values.yaml
          git commit -m "chore: update orbital image tag to $TAG_NAME"
          git push origin main
