release:
  name: Release
  runs-on: ubuntu-latest
  needs: sonar
  if: github.ref == 'refs/heads/main'
  outputs:
    release_tag: ${{ steps.semantic.outputs.new_release_version }}
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Download remote semantic-release configs
      run: |
        curl -o .releaserc.js https://raw.githubusercontent.com/RyuunosukeDS3/git-standards/main/.releaserc.js
        curl -o .releaserc.base.js https://raw.githubusercontent.com/RyuunosukeDS3/git-standards/main/.releaserc.base.js

    - name: Install semantic-release and plugins
      run: |
        npm init -y
        npm install semantic-release \
          @semantic-release/commit-analyzer \
          @semantic-release/release-notes-generator \
          @semantic-release/github \
          @semantic-release/git

    - name: Run semantic-release
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: |
        npx semantic-release
